---
title: "GO Heatmaps"
output: html_notebook
---

Load in GO enrichement data, all eye and body mush vs each other
```{r, message = FALSE}
load('../data/go_enrichment_all_vs_all.Rdata')
library(superheat)
library(tidyverse)
```

GO heatmap of just eye vs body mush
```{r, message = FALSE, fig.height=8.5, fig.width=5}
head(all_vs_all_go)

# select top go ids for up
up_go_ids <- all_vs_all_go %>% 
    filter(Ontology=='BP', grepl('Body', Set),Test=='Up') %>% 
  arrange(as.numeric(`P value (FDR)`)) %>% 
  head(n=40) %>% 
  .[['GO ID']]
# and down
down_go_ids <- all_vs_all_go %>% 
    filter(Ontology=='BP', grepl('Body', Set),Test=='Down') %>% 
  arrange(as.numeric(`P value (FDR)`)) %>% 
  head(n=40) %>% 
  .[['GO ID']]

go_ids <- c(up_go_ids, down_go_ids)
wide_data <- all_vs_all_go %>% 
  filter(Ontology=='BP', grepl('Body', Set), `GO ID` %in% go_ids) %>% 
  separate(Set, c('Comparison','Base'), sep='_vs_') %>% 
   mutate(Comparison=gsub('_',' (',Comparison), 
          Comparison=gsub('Adult.Tissue','adult',Comparison),
          Comparison=gsub('Fetal.Tissue','fetal',Comparison),
          Comparison=gsub('Stem.Cell.Line','stem cell',Comparison),
          Comparison=gsub('Cell.Line','immortalized cell',Comparison),
          Comparison=gsub('$',')', Comparison), 
          Comparison=gsub('cell',' cell', Comparison)) %>% 
   mutate(Base=gsub('_',' (',Base), 
          Base=gsub('Adult.Tissue','adult',Base),
          Base=gsub('Fetal.Tissue','fetal',Base),
          Base=gsub('Stem.Cell.Line','stem cell',Base),
          Base=gsub('Cell.Line','immortalized cell',Base),
          Base=gsub('$',')', Base), 
          Base=gsub('cell',' cell', Base), 
          Base=gsub('Body \\(Tissue\\)','Body (adult)',Base)) %>% 
  mutate(Comparisons = ifelse(Test=='Up', paste(Comparison, Base, sep=' > '), paste(Comparison, Base, sep=' < '))) %>% 
  mutate(`-log10(FDR)` = -log10(as.numeric(`P value (FDR)`))) %>% 
  mutate(`-log10(FDR)` = ifelse(`-log10(FDR)` > 40, 40, `-log10(FDR)`)) %>% 
  mutate(GO = paste(`GO ID`, Term, sep=' ')) %>% 
  dplyr::select(Comparisons, GO, `-log10(FDR)`) %>% 
  spread(Comparisons, `-log10(FDR)`, fill=1)
head(wide_data)
row.names(wide_data) <- wide_data$GO
superheat((wide_data[,2:ncol(wide_data)]),
          #heat.pal = c('#f7fbff','#deebf7','#c6dbef','#9ecae1','#6baed6','#4292c6','#2171b5','#08519c','#08306b'),
          #heat.pal=c("#984ea3","#47039FFF","#7301A8FF","#9C179EFF","#BD3786FF","#D8576BFF","#ED7953FF","#FA9E3BFF","#FDC926FF","#F0F921FF",'white'),
          #heat.pal = viridis(n=10, option = 'plasma'),
          #heat.col.scheme = 
          pretty.order.cols = T, 
          grid.hline.col = 'white', grid.vline.col = 'white',
          force.grid.hline = T,
          pretty.order.rows = T, 
          scale = F, 
          bottom.label.text.angle = 90,
          left.label.size = 1.3,
          bottom.label.size = 0.35, 
          col.dendrogram = F,
          left.label.text.alignment = "left", 
          bottom.label.col = rep(c('#D3F5D5', '#D3E2F5'),10),
          bottom.label.text.alignment = "right")
```


Megalong version
```{r, message = FALSE, fig.height=40, fig.width=15}
head(all_vs_all_go)


```

GO heatmap of just eye vs body mush, removing adult retina from the go id search since a huge amount of the top go ids seem to be retina adult related
```{r, message = FALSE, fig.height=9, fig.width=6}
head(all_vs_all_go)

# select top go ids for up
up_go_ids <- all_vs_all_go %>% 
    filter(Ontology=='BP', grepl('Body', Set),Test=='Up', !grepl('Retina', Set)) %>% 
  arrange(as.numeric(`P value (FDR)`)) %>% 
  head(n=40) %>% 
  .[['GO ID']]
# and down
down_go_ids <- all_vs_all_go %>% 
    filter(Ontology=='BP', grepl('Body', Set),Test=='Down', !grepl('Retina', Set)) %>% 
  arrange(as.numeric(`P value (FDR)`)) %>% 
  head(n=40) %>% 
  .[['GO ID']]

go_ids <- c(up_go_ids, down_go_ids
            )
wide_data <- all_vs_all_go %>% 
  filter(Ontology=='BP', grepl('Body', Set), `GO ID` %in% go_ids) %>% 
  separate(Set, c('Comparison','Base'), sep='_vs_') %>% 
   mutate(Comparison=gsub('_',' (',Comparison), 
          Comparison=gsub('Adult.Tissue','adult',Comparison),
          Comparison=gsub('Fetal.Tissue','fetal',Comparison),
          Comparison=gsub('Stem.Cell.Line','stem cell',Comparison),
          Comparison=gsub('Cell.Line','immortalized cell',Comparison),
          Comparison=gsub('$',')', Comparison), 
          Comparison=gsub('cell',' cell', Comparison)) %>% 
   mutate(Base=gsub('_',' (',Base), 
          Base=gsub('Adult.Tissue','adult',Base),
          Base=gsub('Fetal.Tissue','fetal',Base),
          Base=gsub('Stem.Cell.Line','stem cell',Base),
          Base=gsub('Cell.Line','immortalized cell',Base),
          Base=gsub('$',')', Base), 
          Base=gsub('cell',' cell', Base), 
          Base=gsub('Body \\(Tissue\\)','Body (adult)',Base)) %>% 
  mutate(Comparisons = ifelse(Test=='Up', paste(Comparison, Base, sep=' > '), paste(Comparison, Base, sep=' < '))) %>% 
  mutate(`-log10(FDR)` = -log10(as.numeric(`P value (FDR)`))) %>% 
  mutate(GO = paste(`GO ID`, Term, sep=' ')) %>% 
  dplyr::select(Comparisons, GO, `-log10(FDR)`) %>% 
  spread(Comparisons, `-log10(FDR)`, fill=1)
head(wide_data)
row.names(wide_data) <- wide_data$GO
superheat((wide_data[,2:ncol(wide_data)]), 
          pretty.order.cols = T, 
          pretty.order.rows = T, 
          scale = F, 
          bottom.label.text.angle = 90,
          left.label.size = 0.9,
          bottom.label.size = 0.4, 
          col.dendrogram = T,
          left.label.text.alignment = "left",
          bottom.label.text.alignment = "right")
```

GO heatmap of just eye vs body mush, eye > body
```{r, message = FALSE, fig.height=7, fig.width=5}
head(all_vs_all_go)

# select top go ids for up
up_go_ids <- all_vs_all_go %>% 
    filter(Ontology=='BP', grepl('Body', Set),Test=='Up') %>% 
  arrange(as.numeric(`P value (FDR)`)) %>% 
  head(n=60) %>% 
  .[['GO ID']]


wide_data <- all_vs_all_go %>% 
  filter(Ontology=='BP', grepl('Body', Set), `GO ID` %in% up_go_ids, Test=='Up') %>% 
  separate(Set, c('Comparison','Base'), sep='_vs_') %>% 
   mutate(Comparison=gsub('_',' (',Comparison), 
          Comparison=gsub('Adult.Tissue','adult',Comparison),
          Comparison=gsub('Fetal.Tissue','fetal',Comparison),
          Comparison=gsub('Stem.Cell.Line','stem cell',Comparison),
          Comparison=gsub('Cell.Line','immortalized cell',Comparison),
          Comparison=gsub('$',')', Comparison), 
          Comparison=gsub('cell',' cell', Comparison)) %>% 
   mutate(Base=gsub('_',' (',Base), 
          Base=gsub('Adult.Tissue','adult',Base),
          Base=gsub('Fetal.Tissue','fetal',Base),
          Base=gsub('Stem.Cell.Line','stem cell',Base),
          Base=gsub('Cell.Line','immortalized cell',Base),
          Base=gsub('$',')', Base), 
          Base=gsub('cell',' cell', Base), 
          Base=gsub('Body \\(Tissue\\)','Body (adult)',Base)) %>% 
  mutate(Comparisons = ifelse(Test=='Up', paste(Comparison, Base, sep=' > '), paste(Comparison, Base, sep=' < '))) %>% 
  mutate(`-log10(FDR)` = -log10(as.numeric(`P value (FDR)`))) %>% 
  mutate(GO = paste(`GO ID`, Term, sep=' ')) %>% 
  dplyr::select(Comparisons, GO, `-log10(FDR)`) %>% 
  spread(Comparisons, `-log10(FDR)`, fill=1)
head(wide_data)
row.names(wide_data) <- wide_data$GO
superheat((wide_data[,2:ncol(wide_data)]), 
          pretty.order.cols = T, 
          pretty.order.rows = T, 
          scale = F, 
          bottom.label.text.angle = 90,
          left.label.size = 1.1,
          bottom.label.size = 0.4, 
          col.dendrogram = T,
          left.label.text.alignment = "left",
          bottom.label.text.alignment = "right")
```

```{r, message = FALSE, fig.height=9, fig.width=6}
head(all_vs_all_go)

# select top go ids for up
down_go_ids <- all_vs_all_go %>% 
    filter(Ontology=='BP', grepl('Body', Set),Test=='Down') %>% 
  arrange(as.numeric(`P value (FDR)`)) %>% 
  head(n=60) %>% 
  .[['GO ID']]


wide_data <- all_vs_all_go %>% 
  filter(Ontology=='BP', grepl('Body', Set), `GO ID` %in% down_go_ids, Test=='Down') %>% 
  separate(Set, c('Comparison','Base'), sep='_vs_') %>% 
   mutate(Comparison=gsub('_',' (',Comparison), 
          Comparison=gsub('Adult.Tissue','adult',Comparison),
          Comparison=gsub('Fetal.Tissue','fetal',Comparison),
          Comparison=gsub('Stem.Cell.Line','stem cell',Comparison),
          Comparison=gsub('Cell.Line','immortalized cell',Comparison),
          Comparison=gsub('$',')', Comparison), 
          Comparison=gsub('cell',' cell', Comparison)) %>% 
   mutate(Base=gsub('_',' (',Base), 
          Base=gsub('Adult.Tissue','adult',Base),
          Base=gsub('Fetal.Tissue','fetal',Base),
          Base=gsub('Stem.Cell.Line','stem cell',Base),
          Base=gsub('Cell.Line','immortalized cell',Base),
          Base=gsub('$',')', Base), 
          Base=gsub('cell',' cell', Base), 
          Base=gsub('Body \\(Tissue\\)','Body (adult)',Base)) %>% 
  mutate(Comparisons = ifelse(Test=='Up', paste(Comparison, Base, sep=' > '), paste(Comparison, Base, sep=' < '))) %>% 
  mutate(`-log10(FDR)` = -log10(as.numeric(`P value (FDR)`))) %>% 
  mutate(GO = paste(`GO ID`, Term, sep=' ')) %>% 
  dplyr::select(Comparisons, GO, `-log10(FDR)`) %>% 
  spread(Comparisons, `-log10(FDR)`, fill=1)
head(wide_data)
row.names(wide_data) <- wide_data$GO
superheat((wide_data[,2:ncol(wide_data)]), 
          pretty.order.cols = T, 
          pretty.order.rows = T, 
          scale = F, 
          bottom.label.text.angle = 90,
          left.label.size = 0.9,
          bottom.label.size = 0.4, 
          col.dendrogram = T,
          left.label.text.alignment = "left",
          bottom.label.text.alignment = "right")
```