---
title: "Figure 2"
output: html_notebook
---

```{r, message = FALSE}
library(Rtsne)
library(ggplot2)
library(tidyverse)
library(superheat)
library(ggrepel)
library(RColorBrewer)
library(dbscan)
source('~/git/scripts/theme_Publication.R')
# https://github.com/stephaniehicks/qsmooth
load('~/git/unified_gene_expression/data/lengthScaledTPM_all_2017.Rdata')
load('~/git/unified_gene_expression/data/lengthScaledTPM_processed_2017_02.Rdata')
source('~/git/unified_gene_expression/scripts/parse_sample_attribute.R')
source('~/git/scripts/theme_Publication.R')

core_tight <- core_tight %>% dplyr::select(-run_accession)
core_tight <- core_tight[!duplicated(core_tight),]
core_tight$Tissue = trimws(core_tight$Tissue)
```

Plot eye-only clustering
```{r, fig.width=2.5, fig.height=3.6}
set.seed(23452345)
eye_samples <- core_tight %>% 
  filter(sample_accession %in% colnames(lengthScaledTPM_processed)) %>% 
  filter(!Tissue %in% 'ENCODE Cell Line') %>% 
  filter(study_accession!='SRP012682') %>% 
  filter(!sample_accession %in% c('SRS523795','SRS360124','SRS360123')) %>% 
  .[['sample_accession']] 

eye_TPM <- lengthScaledTPM_processed[,unique(eye_samples)]
perp=35
tsne_out <- Rtsne(as.matrix(log2(t(eye_TPM)+1)),perplexity = perp, check_duplicates = FALSE, theta=0.0)
tsne_plot <- data.frame(tsne_out$Y)
tsne_plot$sample_accession <- colnames(eye_TPM)


# dbscan
dbscan_cluster <- dbscan(tsne_plot %>% dplyr::select(X1,X2), eps=1.4, minPts = 3)
tsne_plot$Cluster <- dbscan_cluster$cluster

# create label points for each cluster
cluster_centers <- tsne_plot %>% 
  left_join(.,core_tight) %>% group_by(Cluster) %>%
  summarise(C1=mean(X1),C2=mean(X2),Tissue=paste(unique(Tissue),collapse=','))

# samples closest to center in each cluster
center_samples <- tsne_plot %>% left_join(.,core_tight)  %>%
    left_join(.,cluster_centers, by=c('Cluster')) %>% 
    mutate(Distance = (X1-C1)+(X2-C2)) %>% 
    group_by(Cluster) %>% 
    dplyr::slice(which.min(Distance)) %>% 
    .[['sample_accession']]

# cluster stats
cluster_stats <- tsne_plot %>% left_join(.,core_tight)  %>% 
  mutate(Origin=factor(Origin, levels=c('Adult Tissue', 'Fetal Tissue', 'Stem Cell Line', 'Cell Line'))) %>% 
  mutate(Cluster = as.factor(Cluster)) %>% 
  group_by(Cluster) %>% 
  summarise(Cluster_Tissues = paste(unique(Tissue), collapse=', '), Cluster_Counts = paste(n(), ' samples', sep=''))

# set up for ggplot
tsne_plot_prep <- tsne_plot %>% left_join(.,core_tight)  %>% 
  mutate(Origin=factor(Origin, levels=c('Adult Tissue', 'Fetal Tissue', 'Stem Cell Line', 'Cell Line'))) %>% 
  mutate(Cluster = as.factor(Cluster)) %>% 
  left_join(., cluster_stats, by=c('Cluster')) %>% 
  mutate(Label = paste(Cluster, Cluster_Tissues,sep=': ')) %>% 
  mutate(Label = ifelse(sample_accession %in% center_samples, Label, ""))

ggplot(tsne_plot_prep,aes(x=X1,y=X2)) + 
  scale_shape_manual(values=c(0:20,35:50)) +
  ggtitle(paste0('Eye tissue t-sne')) +
  geom_point(size=10, alpha=0.2, aes(colour=Cluster)) +
  geom_point(size=4, alpha=0.6, aes(shape=Origin)) + 
  geom_label_repel(aes(label=Label), alpha=0.8, size=4, box.padding = unit(0.4, "lines"))  +
  theme_Publication() + guides(colour=guide_legend(nrow=4), shape=guide_legend(nrow=4)) 
 # geom_density2d(alpha=0.3)

tsne_plot %>% left_join(., core_tight) %>% 
  group_by(Cluster, Tissue, Origin) %>% summarise(Count=n())
```





Plot pan-human tissue expression
```{r, fig.width=3.2, fig.height=3.5}
set.seed(23235)
eye_and_gtex_samples <- core_tight %>% 
  filter(sample_accession %in% colnames(lengthScaledTPM_processed)) %>% 
  filter(!Tissue %in% 'ENCODE Cell Line') %>% 
  filter(!sample_accession %in% c('SRS523795','SRS360124','SRS360123')) %>% 
  filter(!sample_accession %in% c('SRS332999', 'SRS389531', 'SRS626623', 'SRS627133', 'SRS623923', 'SRS629483')) %>% 
  .[['sample_accession']]

eye_and_gtex_TPM <- lengthScaledTPM_processed[,eye_and_gtex_samples]

# tsne
perp=45
tsne_out <- Rtsne(as.matrix(log2(t(eye_and_gtex_TPM)+1)),perplexity = perp, check_duplicates = FALSE, theta=0.0)
tsne_plot <- data.frame(tsne_out$Y)
tsne_plot$sample_accession <- colnames(eye_and_gtex_TPM)

# dbscan
dbscan_cluster <- dbscan(tsne_plot %>% dplyr::select(X1,X2), eps=2)
tsne_plot$Cluster <- dbscan_cluster$cluster

# create label points for each cluster
cluster_centers <- tsne_plot %>% 
  left_join(.,core_tight) %>% 
  mutate(Tissue = ifelse(grepl('fibroblasts',Sub_Tissue),'Fibroblasts',Tissue)) %>% 
  group_by(Cluster) %>%
  summarise(C1=mean(X1),C2=mean(X2),Tissue=paste(unique(Tissue),collapse=','))

# samples closest to center in each cluster
center_samples <- tsne_plot %>% left_join(.,core_tight)  %>%
    left_join(.,cluster_centers, by=c('Cluster')) %>% 
    mutate(Distance = abs((X1-C1)-(X2-C2))) %>% 
    group_by(Cluster) %>% 
    dplyr::slice(which.min(Distance)) %>% 
    .[['sample_accession']]

# cluster stats
cluster_stats <- tsne_plot %>% left_join(.,core_tight)  %>% 
  mutate(Tissue = ifelse(grepl('fibroblasts',Sub_Tissue),' Fibroblasts',Tissue)) %>% 
  mutate(Cluster = as.factor(Cluster)) %>% 
  group_by(Cluster, Tissue) %>% 
  summarise(Cluster_Counts = n(), rTissue = ifelse(Cluster_Counts <= 3, '__', Tissue)) %>%  #Remove outlier tissues from label
  group_by(Cluster) %>% 
  summarise(Cluster_Tissues = paste(unique(rTissue), collapse=', ')) %>% 
  mutate(Cluster_Tissues = gsub('__, ','',Cluster_Tissues))


# set up for ggplot
tsne_plot_prep <- tsne_plot %>% left_join(.,core_tight)  %>% 
  mutate(Tissue = ifelse(grepl('fibroblasts',Sub_Tissue),' Fibroblasts',Tissue)) %>% 
  mutate(Study = study_accession) %>% 
  mutate(Cluster = as.factor(Cluster)) %>%
  left_join(., cluster_stats, by=c('Cluster')) %>% 
  mutate(Label = paste(Cluster, Cluster_Tissues,sep=': ')) %>% 
  mutate(Label = ifelse(sample_accession %in% center_samples, Label, "")) 

ggplot(tsne_plot_prep,aes(x=X1,y=X2)) + 
  ggtitle(paste0('Pan tissue t-sne')) +
  geom_point(size=4, alpha=0.2, aes(colour=Cluster)) +
  geom_point(size=1, alpha=0.2) + 
  geom_label_repel(aes(label=Label), segment.alpha=0.5,alpha=1, size=2.5, box.padding = unit(0.2, "lines"),force=1.2)  +
  theme_Publication() + guides(colour=guide_legend(nrow=4), shape=guide_legend(nrow=4)) 
 # geom_density2d(alpha=0.3)

tsne_plot %>% left_join(., core_tight) %>% 
  group_by(Cluster, Tissue, Origin) %>% summarise(Count=n())

################################
# ID samples to remove upstream
tsne_plot %>% left_join(., core_tight) %>% 
  group_by(Cluster, Tissue, Origin) %>% summarise(Count=n()) %>% filter(Count<=3)
# cluster 9, 1 adipose tissue
# cluster 12, blood vessel, esophagus, and skin are outliers
tsne_plot %>% left_join(.,core_tight) %>% filter(Cluster=='9', Tissue=='Adipose Tissue') # SRS332999
tsne_plot %>% left_join(.,core_tight) %>% 
  filter(Cluster=='12', Tissue %in% c('Blood Vessel', 'Esophagus', 'Skin')) %>% 
  dplyr::select(sample_accession, Tissue, Sub_Tissue, Cluster) # SRS389531, SRS626623, SRS627133, SRS623923, SRS629483
gtex_obvious_outliers <- c('SRS332999', 'SRS389531', 'SRS626623', 'SRS627133', 'SRS623923', 'SRS629483')
```

Heatmap of t-sne distances for pan-tissue. Aggregated across 35 to 50 perplexities and at the tissue level
```{r, fig.width=5, fig.height=6}

load('~/git/unified_gene_expression/data/tsne_plotting_5_50_perplexity_2017-02.Rdata')
mean_coord <- long_tsne_plot %>% 
  filter(perplexity >= 35) %>% 
  group_by(sample_accession) %>% summarise(X1=mean(X1),X2=mean(X2)) %>% # group by sample and summarize across all perplexities
  left_join(.,core_tight) %>% 
  mutate(Tissue = ifelse(grepl('fibroblasts',Sub_Tissue),'Fibroblasts',Tissue)) %>% 
  group_by(Tissue) %>% summarise(X1_mean=mean(X1),X2_mean=mean(X2),varX1=var(X1),varX2=var(X2),variance=varX1+varX2) %>%  # then group by tissue and summarise across all samples in a tissue
  data.frame()


distances <- as.matrix(dist(mean_coord[,2:3])) %>% data.frame() 
colnames(distances) <- mean_coord[,1]                     
row.names(distances) <- mean_coord[,1]
superheat(-distances, 
          #yr = mean_coord$variance,
          #heat.pal = c("#3eb9c4","#87cc5f","white"), # taken from theme_Publication.R
          col.dendrogram = T,
          pretty.order.rows = T, 
          pretty.order.cols = T,
          bottom.label.text.angle = 90,
          bottom.label.text.size = 5, 
          left.label.text.size = 5,
          dist.method = 'euclidean',
          grid.hline.col = "white",
          grid.vline.col = "white")
```

