---
title: "Supplemental Figure S2"
output: html_notebook
---

```{r}
library(Rtsne)
library(ggplot2)
library(formattable)
library(tidyverse)
source('~/git/scripts/theme_Publication.R')
# https://github.com/stephaniehicks/qsmooth
load('~/git/unified_gene_expression/data/lengthScaledTPM_all_2017.Rdata')
load('~/git/unified_gene_expression/data/lengthScaledTPM_processed_01_27_2017.Rdata')
source('~/git/unified_gene_expression/scripts/parse_sample_attribute.R')
```


Samples remaining after QC
```{r}
#Eye
eye_samples <- core_tight %>% 
  filter(sample_accession %in% colnames(lengthScaledTPM_qsmooth_highExp_remove_lowGenes)) %>% 
  filter(!Tissue %in% 'ENCODE Cell Line') %>% 
  filter(study_accession!='SRP012682') %>% 
  filter(!Tissue %in% 'ESC') %>% 
  filter(!sample_accession %in% c('SRS523795','SRS360124','SRS360123')) %>% # these three removed because they group reliably with RPE. See figure_2.Rmd code
  .[['sample_accession']]
#GTEx
GTEx_samples <- core_tight %>% 
  filter(study_accession=='SRP012682') %>% 
  filter(sample_accession %in% colnames(lengthScaledTPM_qsmooth_highExp_remove_lowGenes)) %>% 
  .[['sample_accession']]
```
`r length(eye_samples)` eye samples remaining and `r length(GTEx_samples)` GTEx samples remaining.

Table of all samples that were quantified, marked by whether they failed QC.
```{r}
core_tight %>% 
  filter(sample_accession %in% colnames(lengthScaledTPM)) %>% 
  filter(!Tissue %in% 'ENCODE Cell Line') %>% 
  mutate(QC=ifelse(sample_accession %in% c(eye_samples, GTEx_samples), 'Pass', 'Fail, low median counts')) %>% 
  mutate(QC=ifelse(sample_accession %in% c('SRS523795','SRS360124','SRS360123'), 'Fail, potential tissue mislabel', QC)) %>% 
  arrange(study_accession, Tissue, Origin, QC) %>% 
  select(study_accession, study_title, sample_accession, Tissue, Origin, QC)
```