---
title: "Kmeans cluster gene expression TPM by tissue"
output: html_notebook
---

Load in gene expression and metadata

```{r, message = FALSE}
library(tidyverse)
library(superheat)
load('~/git/unified_gene_expression/data/lengthScaledTPM_processed_2017_02.Rdata')
source('~/git/unified_gene_expression/scripts/parse_sample_attribute.R')

core_tight <- core_tight %>% dplyr::select(-run_accession)
core_tight <- core_tight[!duplicated(core_tight),]
core_tight$Tissue = trimws(core_tight$Tissue)

eye_samples <- core_tight %>% 
  filter(sample_accession %in% colnames(lengthScaledTPM_processed)) %>% 
  filter(!Tissue %in% 'ENCODE Cell Line') %>% 
  filter(!sample_accession %in% c('SRS523795','SRS360124','SRS360123')) %>% 
  filter(study_accession!='SRP012682') %>% 
  #filter(Origin %in% c('Tissue','Adult Tissue')) %>% 
  .[['sample_accession']]
eye_TPM<- lengthScaledTPM_processed[,eye_samples]
```

Reshape to make tall and summarise by tissue then spread again for superheat

```{r, message = FALSE}
tall_summary_TPM <- eye_TPM %>% 
  data.frame() %>% 
  rownames_to_column('Gene.Name') %>% 
  gather(sample_accession, value, -Gene.Name) %>% 
  mutate(sample_accession=gsub('E.MTAB.4377','E-MTAB-4377',sample_accession)) %>% 
  left_join(.,core_tight, by='sample_accession') %>% 
  group_by(Tissue, Origin, Gene.Name) %>% 
  summarise(TPM=mean(value)) %>% 
  mutate(`Tissue and Origin` = paste0(Tissue, ' (', Origin, ')')) %>% 
  ungroup() %>% 
  select(`Tissue and Origin`,Gene.Name,TPM) %>% 
  spread(`Tissue and Origin`, TPM)
```

Quick Superheat plot
```{r, message = FALSE}
superheat(log2(tall_summary_TPM[,2:ncol(tall_summary_TPM)]+1), 
          n.clusters.rows = 20, 
          smooth.heat = T, 
          pretty.order.cols = T)
```